### ISSUE TITLE
API - Could you please add a way to exclude a post from a /blogpost request on the API

### ISSUE THREAD

**Issue by vincentsaisset** [roadiz/AbstractApiTheme#8]
### API
For the **/blogpost** endpoint, could you please add a way to exclude a post from the result.
Via a **@id** or **slug param**.

Useful for relatedPosts request for example.

Thanks in advance.

**Comment by ambroisemaupate** [comment]
![image](https://user-images.githubusercontent.com/380026/113165952-9d54a880-9242-11eb-9568-18fde0ae49e2.png)

**Comment by ambroisemaupate** [comment]
`not` and `not[]` filters are available since v3.1.4
